/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `mobile` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `mobile`;

CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `img` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `categories` (`id`, `img`, `name`) VALUES
	(1, 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:50/q:30/plain/https://cellphones.com.vn/media/wysiwyg/Icon/brand_logo/macbook.png', 'Macbook'),
	(2, 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:50/q:30/plain/https://cellphones.com.vn/media/wysiwyg/Icon/brand_logo/Asus.png', 'Asus'),
	(3, 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:50/q:30/plain/https://cellphones.com.vn/media/wysiwyg/Icon/brand_logo/MSI.png', 'Msi'),
	(4, 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:50/q:30/plain/https://cellphones.com.vn/media/wysiwyg/Icon/brand_logo/Lenovo.png', 'Lenovo'),
	(5, 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:50/q:30/plain/https://cellphones.com.vn/media/wysiwyg/Icon/brand_logo/HP.png', 'Hp'),
	(6, 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:50/q:30/plain/https://cellphones.com.vn/media/wysiwyg/Icon/brand_logo/acer.png', 'Acer'),
	(7, 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:50/q:30/plain/https://cellphones.com.vn/media/wysiwyg/Icon/brand_logo/LG.png', 'LG'),
	(8, 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:50/q:30/plain/https://cellphones.com.vn/media/wysiwyg/Icon/brand_logo/Dell.png', 'Dell');

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `detail` text DEFAULT NULL,
  `img` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `price` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKog2rp4qthbtt2lfyhfo32lsw9` (`category_id`),
  CONSTRAINT `FKog2rp4qthbtt2lfyhfo32lsw9` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=97 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `products` (`id`, `detail`, `img`, `name`, `price`, `category_id`) VALUES
	(71, '- Thiết kế laptop có vỏ ngoài được làm từ kim loại sang trọng, chắc chắc, trọng lượng nhẹ chỉ 999g, thuận tiện cho việc di chuyển. - Sử dụng RAM 16GB cùng ổ cứng 512GB và trang bị thêm 2 khe cắm giúp tăng thêm không gian lưu trữ dữ liệu. - Màn hình 14 inch độ phủ màu DCI-P3 lên đến 99% giúp hình ảnh, video trở nên sống động, rõ nét. - Trang bị bàn phím có đèn led giúp bạn dễ dàng hoạt động trong môi trường thiếu sáng.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/g/lg_gram_20233.png', 'Laptop LG Gram 2023 14Z90RS-G.AH54A5', 28490000, 7),
	(72, '- Chip i5-1340P cùng card đồ họa Intel Iris Xe Graphics giúp bạn thực hiện tốt các công việc văn phòng và giải trị nhẹ. - Ram 16GB cùng ổ cứng 256GB kết hợp với 1 khe trống giúp bạn lưu trữ được nhiều thông tin, dữ liệu. - Màn hình 14.0 inches cùng độ phủ màu DCI-P3 lên đến 99% đem lại chất lượng hình ảnh, video rõ nét. - Âm thanh HD kết hợp cùng Dolby Atmos giúp bạn có những giây phút trải nghiệm âm nhạc chân thật, sống động.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/1/4/14z90r.png', 'Laptop LG Gram 2023 14Z90R-G.AH53A5', 23990000, 7),
	(73, '- Chip i5-1340P kết hợp cùng đồ họa Intel Iris Xe Graphics giúp bạn giải quyết tốt các tác vụ văn phòng cũng như chỉnh sửa nhẹ hình ảnh. - Màn hình 15.6 inch có độ phân giải Full HD kết hợp cùng độ phủ màu DCI-P3 100% đem trải nghiệm hình ảnh, video chân thật. - RAM 16GB cùng ổ cứng SSD 512GB đem lại không gian lưu trữ dữ liệu rộng lớn.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/a/laptop-lg-gram-2023-15z90rt-g-ah55a5.png', 'Laptop LG Gram 2023 15Z90RT-G.AH55A5', 31990000, 7),
	(74, '- Chip i7-1360P kết hợp cùng RTX 3050 giúp bạn thoả sức chỉnh sức hình ảnh, đồ hoạ. - Màn hình 14 inch có độ phân giải WQXGA kết hợp cùng độ phủ màu DCI-P3 99% đem lại khả năng hiển thị hình ảnh sắc nét và màu sắc chân thật. - Sử dụng nhiều cổng kết nối: Cổng USB Type C, USB Type A, HDMI, DC-in, giúp bạn truyền và xuất dữ liệu một cách nhanh chóng.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/g/lg_gram_3050.png', 'Laptop LG Gram 2023 16Z90R-E.AH75A5', 36990000, 7),
	(75, '- Trải nghiệm khung hình sắc nét, sống động - Màn hình 14 inches, đi kèm độ phân giải FullHD+. - Cấu hình mạnh mẽ, xử lí tốc độ - Chip CPU Intel Core i7-1165G7, 16 GB RAM. - Năng lượng tràn đầy cả ngày dài - Viên pin 80 Wh cho thời gian dùng lên đến 9 tiếng. - Làm việc thuận tiện hơn với bàn phím được trang bị đèn nền 2 mức độ sáng.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/a/1/a17k_4__1.jpg', 'Laptop LG Gram 2021 14Z90P-G.AH75A5 14 inch', 24990000, 7),
	(76, '- Chip i5-1340P cùng đồ họa Intel Iris Xe Graphics giúp bạn có thể chiến được những tựa game nhẹ, chỉnh sửa hình ảnh. - Màn hình 16 inch có độ phân giải WQXGA và độ phủ màu DCI-P3 99% giúp hình ảnh, video trở nên sắc nét, chân thật. - Trang bị nhiều cổng kết nối khác nhau, giúp bạn thuận tiện trong việc kết nối và truyền tải dữ liệu - Cổng USB Type C, USB Type A, HDMI, DC-in. - Thiết kế kiểu dáng gọn nhẹ, sang trọng, trọng lượng chỉ 1.199kg giúp bạn mang theo bên mình dễ dàng.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_d_i_7__1.png', 'Laptop LG Gram 2023 16ZD90R-G.AX55A5', 28990000, 7),
	(77, '- Thiết kế kiểu dáng thanh lịch, dễ dàng mang theo mọi nơi - Có độ mỏng 16.8mm và nhẹ 999g. - Chip i7-1360P kết hợp cùng card đồ họa Intel Iris Xe Graphics cho phép bạn thực hiện những công việc văn phòng cũng như chỉnh sửa hình ảnh trên PTS. - Trang bị màn hình 14 inch WUXGA tích hợp cùng độ phủ màu DCI-P3 99% đem đến những hình ảnh, thước phim rõ nét, chân thật.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/a/laptop-lg-gram-2023-14z90r-g-ah75a5.png', 'Laptop LG Gram 2023 14Z90R-G.AH75A5', 26890000, 7),
	(78, '- Chip i5-1340P kết hợp cùng Intel Iris Xe Graphics đem lại nhiều tiện ích trong việc giải quyết công việc văn phòng cũng như chỉnh sửa nhẹ hình ảnh. - Màn hình 14 inch kết hợp cùng độ phủ màu DCI-P3 99% và công nghệ chống chói giúp bạn trải nghiệm được hình ảnh sống động nhưng vẫn bảo vệ được đôi mắt. - RAM 16GB cùng ổ cứng SSD 512GB giúp bạn tự tin lưu trữ dữ liệu mà không sợ hết.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_d_i_15_.png', 'Laptop LG GRAM 2IN1 14T90R-G.AH55A5', 28990000, 7),
	(79, '- Chip i5-1340P kết hợp cùng Intel Iris Xe Graphics đem lại nhiều tiện ích trong việc giải quyết công việc văn phòng cũng như chỉnh sửa nhẹ hình ảnh. - Màn hình 16 inch kết hợp cùng độ phủ màu DCI-P3 100% và công nghệ chống chói giúp bạn trải nghiệm được hình ảnh sống động nhưng vẫn bảo vệ được đôi mắt. - RAM 16GB cùng ổ cứng SSD 512GB giúp bạn tự tin lưu trữ dữ liệu mà không sợ hết. - Thiết kế laptop mỏng nhẹ, trọng lượng chỉ 1.25kg , rất dễ dàng để bạn mang theo bên người mà không lo nặng vai.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/g/lg_gram_20233.png', 'Laptop LG GRAM 2023 16Z90RS-G.AH54A5', 33990000, 7),
	(81, '- Thiết kế đơn giản, trẻ trung với tone màu đen bao phủ.. - Màn hình cảm ứng 15.6 inch Full HD cho trải nghiệm hình ảnh vô cùng sắc nét.. - CPU Intel core i5-1155G7 cùng 8 GB RAM DDR4 xử lý mượt các tác vụ văn phòng: Word, Excel,... - Card đồ họa Intel Iris Xe Graphics hỗ trợ chỉnh ảnh đơn giản. - Không gian lưu trữ vừa phải với ổ cứng 256 GB SSD.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_2__4_28.png', 'Laptop Dell Inspiron 15 3520-5810BLK 102F0', 12790000, 8),
	(82, '- Sở hữu thiết kế thanh lịch và đầy chuyên nghiệp, màu đen làm tăng vẻ sang trọng. - Trang bị vi xử lý Intel Core i3-1215U đem lại hiệu năng ổn định cho công việc hàng ngày và xử lý đa nhiệm mượt mà. - Bộ nhớ RAM 8GB và ổ cứng SSD PCIe 512GB giúp khởi động và truy cập dữ liệu nhanh chóng. - Màn hình 15.6 inch FHD tạo ra hình ảnh sắc nét, giúp nâng cao trải nghiệm làm việc và giải trí. - Laptop này chạy trên Free OS, cho phép người dùng tự do chọn hệ điều hành phù hợp với nhu cầu của mình.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/a/laptop-dell-vostro-3520-f0v0vi3-thumbnails.png', 'Laptop Dell Vostro 3520 F0V0VI3', 9690000, 8),
	(83, '- Trang bị bộ vi xử lý Intel Core i5-1235U xử lý một loạt các nhiệm vụ từ lướt web, soạn thảo văn bản, chỉnh sửa hình ảnh đơn giản. - RAM 8GB, một dung lượng đủ lớn để chạy nhiều ứng dụng cùng một lúc mà không gây ra hiện tượng máy bị giật lag hay đứng máy. - Ổ cứng SSD PCIe 256GB, giúp tăng tốc độ truy cập dữ liệu và khởi động máy nhanh chóng. - Màn hình Full HD 15.6 inch mang đến hình ảnh rõ nét và màu sắc trung thực. - Hệ điều hành Free OS, cho phép bạn tự do lựa chọn hệ điều hành phù hợp với nhu cầu sử dụng của mình.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/a/laptop-dell-vostro-3520-f0v0v256-thumbnails.png', 'Laptop Dell Vostro 3520 F0V0V256', 12490000, 8),
	(84, '- Sở hữu thiết kế cá tính với màu đen mạnh mẽ. - Màn hình15.6 inch cùng cân nặng chỉ 1.90 kg dễ dàng bỏ laptop vào balo hay túi xách. - CPU Intel Core i5-1235U kết hợp card đồ họa Intel Iris Xe Graphics xử lý tốt các tác vụ nặng nhẹ khác nhau. - RAM 8 GB cùng ổ cứng 256 GB SSD đa nhiệm cực tốt, mở cùng lúc hàng chục tabs trên Google Chrome mà không lo bị giật lag. - Hỗ trợ Webcam, cho bạn thoải mái học online, làm việc trực tuyến,...', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_9__3_24.png', 'Laptop Dell Inspiron 15 3520 YTC9K', 12590000, 8),
	(85, '- Hiệu năng ổn định với I7-1235U xử lý tốt các tác vụ từ văn phòng đến chỉnh sứa hình ảnh. - RAM 8 GB tối ưu hoá tốt hiệu suất sử dụng, cho phép mở nhiều ứng dụng cùng lúc. - SSD 512 GB NVMe tốc độ cao rút ngắn thời gian load ứng dụng. - Giải trí sống động với màn hình 15.6 inch cùng độ phân giải full HD.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/a/laptop_dell_vostro_3520i7.png', 'Laptop Dell Vostro 3520', 18490000, 8),
	(86, '- CPU Intel Core i5 1135G7 xử lý mượt mà các tác vụ như lướt web, soạn thảo săn bản, xem phim, giải trí. - Bộ nhớ RAM 8 GB đáp ứng các tác vụ học tập, làm việc văn phòng. - Card đồ họa Iris Xe Graphics dễ dàng sử dụng đồ họa ở mức cơ bản, chẳng hạn như xem video, xem phim hoặc chỉnh sửa hình ảnh đơn giản. - Ổ cứng SSD 512 GB rộng rãi, thoải mái lưu trữ tài liệu học tập, phim ảnh. - Màn hình lớn 15.6 inch Full HD rộng lớn và đã mắt với chất lượng hình ảnh hiển thị rõ nét, trung thực.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_6__152.png', 'Laptop Dell Vostro 3520 GD02R', 12490000, 8),
	(87, '- CPU Intel Core i3 1115G4 và card Intel UHD Graphics yên tâm vận hành các tác vụ học tập, văn phòng hay giải trí dễ dàng. - RAM 8 GB DDR4 cho phép bạn chạy đồng thời nhiều chương trình mà không gặp trở ngại. - Ổ cứng SSD 256 GB sẽ cung cấp không gian lưu trữ vừa đủ cho nhiều tập tin, hình ảnh, video và tài liệu quan trọng. - Màn hình 15.6 inch Full HD cho bạn độ nét cao và hình ảnh sắc nét.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_6_9.png', 'Laptop Dell Inspiron 15 3520 D5N53', 9990000, 8),
	(88, '- Thiết kế thời thượng cùng bản lề mở gập được 360 độ, cùng màn hình cảm ứng hỗ trợ thao tác dễ dàng. - CPU Intel Core i7 1355U, hỗ trợ vận hành hoàn hảo mọi công việc văn phòng như soạn thảo văn bản, Word, Excel,... - Card Intel Iris Xe Graphics với khả năng xử lý các tác vụ chỉnh sửa hình ảnh đơn giản, thiết kế poster, banner,... - Không hề có hiện tượng bị đơ lại, độ đa nhiệm luôn được đảm bảo hiệu quả nhờ bộ nhớ RAM 16 GB. - Ổ cứng SSD 1 TB đủ lớn, giúp lưu trữ các tài liệu về công việc cũng như giải trí, tốc độ truy xuất dữ liệu cao.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_32__1_6.png', 'Laptop Dell Inspiron 14 I7430-7374SLV CN29D', 12190000, 8),
	(89, '- Bộ vi xử lý Intel Core i7 1255U xử lý nhanh chóng và hiệu quả các tác vụ thường ngày như soạn thảo săn bản, xem phim, giải trí hay chỉnh sửa video, hình ảnh và chơi game ở mức cấu hình trung bình. - RAM 8 GB thực hiện nhanh gọn các tác vụ, mở đồng thời hàng chục tab Chrome mà không lo giật lag gây gián đoạn trong quá trình sử dụng. - Ổ cứng SSD 512 GB có tốc độ đọc, ghi cao, rút ngắn đáng kể thời gian phản hồi, khởi động máy. - Màn hình lớn 15.6 inch Full HD mang đến góc nhìn được tối ưu, rộng lớn và đã mắt với chất lượng hình ảnh hiển thị rõ nét, trung thực. - Tần số quét 120 Hz cho mọi thao tác mượt mà, nâng cao trải nghiệm chơi game.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_19__1_5.png', 'Laptop Dell Vostro 3520 Y4G15', 17490000, 8),
	(90, '- Sở hữu vẻ ngoài tối giản, sang trọng, phù hợp cho nhiều đối tượng người dùng. - Màn hình 15.6 inch Full HD rộng rãi, cho không gian làm việc, giải trí thoải mái. - CPU AMD R5-5500U mạnh mẽ, xử lý nhanh gọn mọi tác vụ văn phòng, học tập nhanh chóng. - RAM 8GB đa nhiệm cho khả năng mở nhiêu tabs Chrome cùng lúc mà không lo lag, giật. - Ổ cứng 512GB SSD rộng rãi, hỗ trợ mở máy nhanh chóng.', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_d_i_3_3.png', 'Laptop Dell Inspiron 15 3525', 12290000, 8);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
